# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171122_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='state_license_state',
            field=models.CharField(blank=True, max_length=255, verbose_name="State licence's state"),
        ),
    ]
