# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 04:01
from __future__ import unicode_literals

import apps.accounts.models.resident
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_resident_state_license_state'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='resident',
            managers=[
                ('objects', apps.accounts.models.resident.ResidentManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
    ]
