# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171204_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='residency_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='accounts.ResidencyProgram', verbose_name='Residency program'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='specialities',
            field=models.ManyToManyField(blank=True, related_name='residents', to='accounts.Speciality', verbose_name='Specialities'),
        ),
    ]
