# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_remove_shift_residency_program'),
        ('accounts', '0006_auto_20171206_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='residency_program',
            field=models.TextField(blank=True, null=True, verbose_name='Residency program'),
        ),
        migrations.DeleteModel(
            name='ResidencyProgram',
        ),
    ]
