# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 05:34
from __future__ import unicode_literals

import apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180119_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=apps.accounts.fields.AvatarField(blank=True, null=True, upload_to=apps.accounts.fields.ClassNameUploadPath('avatars')),
        ),
    ]
