# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180119_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='cv_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link to CV'),
        ),
    ]
