# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='cv_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to CV'),
        ),
    ]
