# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_auto_20171206_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='residency_program',
        ),
    ]
