# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_remove_shift_residency_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
