# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 06:07
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def initialize_dbmail_templates(apps, schema_editor):
    call_command('init_dbmail_templates')


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_dbmail_templates)
    ]
