# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 04:36
from __future__ import unicode_literals

from django.db import migrations


def change_mail_headers(apps, schema_editor):
    MailTemplate = apps.get_model("dbmail", "MailTemplate")

    MailTemplate.objects.filter(slug='shift_created').update(
        subject='A new suitable shift for you: {{ shift.speciality_name }} at '
                '{{ shift.date_start }}'
    )

    MailTemplate.objects.filter(slug='shift_updated').update(
        subject='A shift was updated: {{ shift.speciality_name }} at '
                '{{ shift.date_start }}'
    )

    MailTemplate.objects.filter(slug='shift_deleted').update(
        subject='A shift was deleted: {{ shift.speciality_name }} at '
                '{{ shift.date_start }}'
    )


def clean_cache(apps, schema_editor):
    from dbmail.models import MailTemplate, ApiKey

    MailTemplate.clean_cache()
    ApiKey.clean_cache()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_mail_headers),
        migrations.RunPython(clean_cache),
    ]
